version: "3"
services:
  nginx:
    ports:
      - "8000:80"
  node-app:
    build:
      context: .
      args:
        - NODE_ENV=development
    volumes:
      - ./:/app
      - /app/node_modules
    command: yarn run dev
