name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and tag Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            920108834017.dkr.ecr.us-east-1.amazonaws.com/node-app:latest

      - name: Push Docker image to Amazon ECR
        if: success() && steps.build-image.outputs.pushed == 'true'
        env:
          ECR_REGISTRY: 920108834017.dkr.ecr.us-east-1.amazonaws.com
          IMAGE_NAME: node-app
        run: |
          docker tag 920108834017.dkr.ecr.us-east-1.amazonaws.com/node-app:latest $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          
      - name: Deploy to Amazon ECS
        if: success() && steps.build-image.outputs.pushed == 'true'
        uses: aws-actions/amazon-ecs-deploy-task@v2
        with:
          cluster: cluster1
          service: node-app-service
          task_definition: node-app-definition
          container_name: node-app-container
          image: 920108834017.dkr.ecr.us-east-1.amazonaws.com/node:latest