name: Build and Deploy to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 920108834017
  ECS_CLUSTER: Cluster1
  ECS_SERVICE: node-app-service
  ECS_TASK_DEFINITION: node-app-definition
  ECS_CONTAINER: node-app-container
  ECR_REPOSITORY: node-app

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and tag Docker image
        id: build-image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: |
            ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest

      - name: Push Docker image to Amazon ECR
        if: success() && steps.build-image.outputs.pushed == 'true'
        env:
          ECR_REGISTRY: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com
          IMAGE_NAME: ${{ env.ECR_REPOSITORY }}
        run: |
          docker tag ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA
          docker push $ECR_REGISTRY/$IMAGE_NAME:$GITHUB_SHA

      - name: Create new ECS task definition
        id: create-task-def
        run: |
          echo ::set-output name=task-def::$(aws ecs register-task-definition \
            --family "${{ env.ECS_SERVICE }}" \
            --container-definitions "$(cat task-def.json)" \
            --requires-compatibilities FARGATE \
            --cpu 256 \
            --memory 512 \
            --network-mode awsvpc \
            --execution-role-arn "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-task-execution-role" \
            --task-role-arn "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/my-task-role" \
            --region "${{ env.AWS_REGION }}" \
            --output json \
          )

      - name: Update ECS service to use new task definition
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ env.ECS_SERVICE }}" \
            --task-definition "${{ steps.create-task-def.outputs.task-def }}"